SYS = vic20




build:
	cl65 -t c64 prompt2.c -o /output/musicprompt2.prg
	cl65 -t $(SYS) hello.c -o /output/hello-vic20.prg
	cl65 -t $(SYS) petscii.c -o /output/petscii.prg
	cl65 -t $(SYS) printf.c -o /output/printf.prg
	cl65 -t $(SYS) rasterhax.c -o /output/rasterhax.prg
	cl65 -t $(SYS) rasterhax2.c -o /output/rasterhax2.prg